--BỆNH NHÂN
--Taọ proc để lấy toàn bộ bệnh nhân
CREATE PROC SelectAllBenhNhan 
	@TUKHOA NVARCHAR(50) --tìm kiếm bệnh nhân dựa vào từ khóa
	--1. tìm theo mã bệnh nhân
	--2. tìm theo tên, 
	--3. tìm theo số điện thoại
	-- loại tìm kiếm tương đối
AS
	SELECT 
		MABN,
		TENBN,
		GIOITINH,
		CONVERT (VARCHAR (10), NGAYSINH, 103) AS NGAYSINH, --định dạng ngày sinh theo dd/mm/yyyy
		DIACHI,
		SODIENTHOAI,
		TINHTRANGSUCKHOE
	FROM BENHNHAN
	WHERE
		CAST(MABN AS VARCHAR(10)) LIKE '%' + LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(TENBN) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(GIOITINH) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(NGAYSINH) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(DIACHI) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(SODIENTHOAI) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(TINHTRANGSUCKHOE) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
	ORDER BY TENBN
GO
--thực thi proc
EXEC SelectAllBenhNhan 'bn001'



--Tạo proc để thêm mới một bệnh nhân vào bảng BENHNHAN
CREATE PROC ThemMoiBN
	@mabn VARCHAR(10),
	@tenbn NVARCHAR(50),
	@gioitinh NVARCHAR(5),
	@ngaysinh DATE,
	@diachi NVARCHAR(100),
	@sodienthoai VARCHAR(10),
	@tinhtrangsuckhoe NVARCHAR(100)
AS
BEGIN 
	--THÊM DỮ LIỆU MỚI
	INSERT INTO BENHNHAN
	(
		MABN,
		TENBN,
		GIOITINH,
		NGAYSINH,
		DIACHI,
		SODIENTHOAI,
		TINHTRANGSUCKHOE
	)
	VALUES
	(
		@mabn,
		@tenbn,
		@gioitinh,
		@ngaysinh,
		@diachi,
		@sodienthoai,
		@tinhtrangsuckhoe
	);
	--KIỂM TRA XEM ĐÃ INSERT THÀNH CÔNG HAY CHƯA
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END




-- TẠO PROCEDURE UPDATE THÔNG TIN BỆNH NHÂN
CREATE PROC UpdateBN
	@MABN VARCHAR(10),
	@TENBN NVARCHAR(50),
	@GIOITINH NVARCHAR(5),
	@NGAYSINH DATE,
	@DIACHI NVARCHAR(100),
	@SODIENTHOAI VARCHAR(10),
	@TINHTRANGSUCKHOE NVARCHAR(100)
AS 
BEGIN
	UPDATE BENHNHAN
	SET
		MABN=@MABN,
		TENBN=@TENBN,
		GIOITINH=@GIOITINH,
		NGAYSINH=@NGAYSINH,
		DIACHI=@DIACHI,
		SODIENTHOAI=@SODIENTHOAI,
		TINHTRANGSUCKHOE=@TINHTRANGSUCKHOE
	WHERE MABN = @MABN;
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END





--TẠO PROC SELECT THÔNG TIN CHI TIẾT CỦA 1 BỆNH NHÂN
CREATE PROC selectBN
	@MABN VARCHAR(10)
AS
BEGIN
	SELECT
		MABN,
		TENBN,
		GIOITINH,
		CONVERT (VARCHAR (10), NGAYSINH, 103) AS NGAYSINH, --định dạng ngày sinh theo dd/mm/yyyy
		DIACHI,
		SODIENTHOAI,
		TINHTRANGSUCKHOE
	FROM BENHNHAN
WHERE MABN = @MABN;
END



--TẠO PROC ĐỂ XÓA THÔNG TIN BỆNH NHÂN
CREATE PROC DeleteBN
	@MABN VARCHAR(10)
AS
BEGIN
	--XÓA CÁC DỮ LIỆU CHI TIẾT HÓA ĐƠN DỊCH VỤLIÊN QUAN TỚI HÓA ĐƠN CỦA BỆNH NHÂN CẦN XÓA 
	DELETE FROM HOADON_DV WHERE MAHD IN (SELECT MADT FROM DONTHUOC WHERE MABN = @MABN);
	DELETE FROM HOADON WHERE MABN = @MABN --xóa các hóa đơn của của bệnh nhân đó
	--XÓA CÁC DỮ LIỆU CHI TIẾT ĐƠN THUỐC LIÊN QUAN TỚI ĐƠN THUỐC CỦA BỆNH NHÂN
	DELETE FROM CT_DONTHUOC WHERE MADT IN (SELECT MADT FROM DONTHUOC WHERE MABN = @MABN);
	DELETE FROM DONTHUOC WHERE MABN = @MABN --xóa các đơn thuốc của bệnh nhân đó
	DELETE FROM BENHNHAN WHERE MABN = @MABN
IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END


-----------------------------------------------------------------------------
--BÁC SĨ
--Taọ proc để lấy toàn bộ bác sĩ
CREATE PROC SelectAllBacSi 
	@TUKHOA NVARCHAR(50) --tìm kiếm bác sĩ dựa vào từ khóa
	--1. tìm theo mã bác sĩ
	--2. tìm theo tên, 
	--3. tìm theo chuyên ngành
	-- loại tìm kiếm tương đối
AS
	SELECT 
		MABS,
		TENBS,
		CHUYENNGANH
	FROM BACSI
	WHERE
		CAST(MABS AS VARCHAR(10)) LIKE '%' + LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(TENBS) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(CHUYENNGANH) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
	ORDER BY TENBS
GO



--Tạo proc để thêm mới một bác sĩ vào bảng BACSI
CREATE PROC ThemMoiBS
	@mabs VARCHAR(10),
	@tenbs NVARCHAR(50),
	@chuyennganh NVARCHAR(30)
AS
BEGIN 
	--THÊM DỮ LIỆU MỚI
	INSERT INTO BACSI
	(
		MABS,
		TENBS,
		CHUYENNGANH
	)
	VALUES
	(
		@mabs,
		@tenbs,
		@chuyennganh
	);
	--KIỂM TRA XEM ĐÃ INSERT THÀNH CÔNG HAY CHƯA
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END



-- TẠO PROCEDURE UPDATE THÔNG TIN BÁC SĨ
CREATE PROC UpdateBS
	@MABS VARCHAR(10),
	@TENBS NVARCHAR(50),
	@CHUYENNGANH NVARCHAR(30)
AS 
BEGIN
	UPDATE BACSI
	SET
		MABS=@MABS,
		TENBS=@TENBS,
		CHUYENNGANH=@CHUYENNGANH
	WHERE MABS = @MABS;
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END



--TẠO PROC SELECT THÔNG TIN CHI TIẾT CỦA 1 BÁC SĨ
CREATE PROC selectBS
	@MABS VARCHAR(10)
AS
BEGIN
	SELECT
		MABS,
		TENBS,
		CHUYENNGANH
	FROM BACSI
WHERE MABS = @MABS;
END



--TẠO PROC ĐỂ XÓA THÔNG TIN BÁC SĨ
CREATE PROC DeleteBS
	@MABS VARCHAR(10)
AS
BEGIN
	--XÓA CÁC DỮ LIỆU ĐƠN THUỐC LIÊN QUAN TỚI ĐƠN THUỐC MÀ BÁC SĨ CẦN XÓA ĐÃ KÊ ĐƠN THUỐC
	DELETE FROM CT_DONTHUOC WHERE MADT IN (SELECT MADT FROM DONTHUOC WHERE MABS = @MABS);
	DELETE FROM DONTHUOC WHERE MABS = @MABS --xóa các đơn thuốc được kê đơn từ bác sĩ đó
	DELETE FROM BACSI WHERE MABS = @MABS
IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END



-------------------------------------------------------------------------
--Taọ proc để lấy toàn bộ thông tin thuốc
CREATE PROC SelectAllThuoc 
	@TUKHOA NVARCHAR(50) --tìm kiếm thuốc dựa vào từ khóa
	--1. tìm theo mã THUỐC
	--2. tìm theo tên THUỐC
	-- loại tìm kiếm tương đối
AS
	SELECT 
		MATHUOC,
		TENTHUOC,
		GIATHUOC
	FROM THUOC
	WHERE
		CAST(MATHUOC AS VARCHAR(10)) LIKE '%' + LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(TENTHUOC) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(GIATHUOC) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
	ORDER BY TENTHUOC
GO



--Tạo proc để thêm mới thuốc vào bảng THUOC
CREATE PROC ThemMoiThuoc
	@mathuoc VARCHAR(10),
	@tenthuoc NVARCHAR(30),
	@giathuoc FLOAT
AS
BEGIN 
	--THÊM DỮ LIỆU MỚI
	INSERT INTO THUOC
	(
		MATHUOC,
		TENTHUOC,
		GIATHUOC
	)
	VALUES
	(
		@mathuoc,
		@tenthuoc,
		@giathuoc
	);
	--KIỂM TRA XEM ĐÃ INSERT THÀNH CÔNG HAY CHƯA
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END



-- TẠO PROCEDURE UPDATE THÔNG TIN THUỐC
CREATE PROC UpdateThuoc
	@MATHUOC VARCHAR(10),
	@TENTHUOC NVARCHAR(30),
	@GIATHUOC FLOAT
AS 
BEGIN
	UPDATE THUOC
	SET
		MATHUOC=@MATHUOC,
		TENTHUOC=@TENTHUOC,
		GIATHUOC=@GIATHUOC
	WHERE MATHUOC = @MATHUOC;
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END



--TẠO PROC SELECT THÔNG TIN CHI TIẾT CỦA THUỐC
CREATE PROC selectThuoc
	@MATHUOC VARCHAR(10)
AS
BEGIN
	SELECT
		MATHUOC,
		TENTHUOC,
		GIATHUOC
	FROM THUOC
WHERE MATHUOC=@MATHUOC;
END



--TẠO PROC ĐỂ XÓA THÔNG TIN THUỐC
CREATE PROC DeleteThuoc
	@MATHUOC VARCHAR(10)
AS
BEGIN
	--XÓA CÁC DỮ LIỆU ĐƠN THUỐC LIÊN QUAN TỚI CT_ĐƠN THUỐC CỦA THUỐC ĐÓ
	DELETE FROM DONTHUOC WHERE MADT IN (SELECT MADT FROM CT_DONTHUOC WHERE MATHUOC = @MATHUOC);
	DELETE FROM CT_DONTHUOC WHERE MATHUOC = @MATHUOC --xóa các chi tiết đơn thuốc liên quan tới thuốc
	DELETE FROM THUOC WHERE MATHUOC = @MATHUOC
IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END


-------------------------------------------------------
--Taọ proc để lấy toàn bộ thông tin DỊCH VỤ KHÁM
CREATE PROC SelectAllDVKham 
	@TUKHOA NVARCHAR(50) --tìm kiếm thuốc dựa vào từ khóa
	--1. tìm theo mã DV
	--2. tìm theo tên DV
	-- loại tìm kiếm tương đối
AS
	SELECT 
		MADV,
		TENDV,
		GIADV
	FROM DVKHAM
	WHERE
		CAST(MADV AS VARCHAR(10)) LIKE '%' + LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(TENDV) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(GIADV) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
	ORDER BY TENDV
GO





--Tạo proc để thêm mới DỊCH VỤ KHÁM vào bảng DVKHAM
CREATE PROC ThemMoiDVKham
	@madv VARCHAR(10),
	@tendv NVARCHAR(30),
	@giadv FLOAT
AS
BEGIN 
	--THÊM DỮ LIỆU MỚI
	INSERT INTO DVKHAM
	(
		MADV,
		TENDV,
		GIADV
	)
	VALUES
	(
		@madv,
		@tendv,
		@giadv
	);
	--KIỂM TRA XEM ĐÃ INSERT THÀNH CÔNG HAY CHƯA
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END



-- TẠO PROCEDURE UPDATE THÔNG TIN DỊCH VỤ KHÁM
CREATE PROC UpdateDVKham
	@MADV VARCHAR(10),
	@TENDV NVARCHAR(30),
	@GIADV FLOAT
AS 
BEGIN
	UPDATE DVKHAM
	SET
		MADV=@MADV,
		TENDV=@TENDV,
		GIADV=@GIADV
	WHERE MADV = @MADV;
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END





--TẠO PROC SELECT THÔNG TIN CHI TIẾT CỦA DỊCH VỤ KHÁM
CREATE PROC selectDVKham
	@MADV VARCHAR(10)
AS
BEGIN
	SELECT
		MADV,
		TENDV,
		GIADV
	FROM DVKHAM
WHERE MADV=@MADV;
END



--TẠO PROC ĐỂ XÓA THÔNG TIN DỊCH VỤ KHÁM
CREATE PROC DeleteDVKham
	@MADV VARCHAR(10)
AS
BEGIN
	--XÓA CÁC DỮ LIỆU HÓA ĐƠN LIÊN QUAN TỚI CHI TIẾT HÓA ĐƠN DV CỦA DV KHÁM ĐÓ
	DELETE FROM HOADON WHERE MAHD IN (SELECT MAHD FROM HOADON_DV WHERE MADV = @MADV);
	DELETE FROM HOADON_DV WHERE MADV = @MADV --xóa các chi tiết HÓA ĐƠN DỊCH VỤ KHÁM LIÊN QUAN TỚI DV KHÁM
	DELETE FROM DVKHAM WHERE MADV = @MADV
IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END



------------------------------------------------------------------
--Taọ proc để lấy toàn bộ thông tin đơn thuốc
CREATE PROC SelectAllDonThuoc
	@TUKHOA NVARCHAR(50) --tìm kiếm đơn thuốc dựa vào từ khóa
	--1. tìm theo mã ĐƠN THUỐC
	--3. TÌM THEO TÊN BÁC SĨ
	--4. TÌM THEO TÊN BỆNH NHÂN
	-- loại tìm kiếm tương đối
AS
	SELECT 
		DT.MADT,BS.TENBS,BN.TENBN
	FROM DONTHUOC DT
	JOIN BENHNHAN BN ON DT.MABN=BN.MABN
	JOIN BACSI BS ON DT.MABS=BS.MABS
	WHERE
		CAST(DT.MADT AS VARCHAR(10)) LIKE '%' + LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(BS.MABS) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(BS.TENBS) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(BN.MABN) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(BN.TENBN) LIKE '%'+LOWER(TRIM(@TUKHOA)) + '%'
	ORDER BY DT.MADT
GO

--Tạo proc để thêm mới đơn thuốc vào bảng DONTHUOC
CREATE PROC ThemMoiDonThuoc
	@madt VARCHAR(10),
	@mabs VARCHAR(10),
	@mabn VARCHAR(10)
AS
BEGIN 
	--THÊM DỮ LIỆU MỚI
	INSERT INTO DONTHUOC
	
(
		MADT,
		MABS,
		MABN
	)
	VALUES
	(
		@madt,
		@mabs,
		@mabn
	);
	--KIỂM TRA XEM ĐÃ INSERT THÀNH CÔNG HAY CHƯA
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END


-- TẠO PROCEDURE UPDATE THÔNG TIN đơn thuốc
CREATE PROC UpdateDonThuoc
	@MADT VARCHAR(10),
	@MABS VARCHAR(10),
	@MABN VARCHAR(10)
AS 
BEGIN
	UPDATE DONTHUOC
	SET
		MADT=@MADT,
		MABS=@MABS,
		MABN=@MABN
	WHERE MADT = @MADT;
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END


--TẠO PROC SELECT THÔNG TIN ĐƠN THUỐC
CREATE PROC selectDonThuoc
	@MADT VARCHAR(10)
AS
BEGIN
	SELECT
		MADT,
		MABS,
		MABN
	FROM DONTHUOC
WHERE MADT=@MADT;
END



--TẠO PROC ĐỂ XÓA THÔNG TIN ĐƠN THUỐC
CREATE PROC DeleteDonThuoc
	@MADT VARCHAR(10)
AS
BEGIN
	DELETE FROM CT_DONTHUOC WHERE MADT = @MADT --xóa các chi tiết DƠN THUỐC LIÊN QUAN TỚI ĐƠN THUỐC
	DELETE FROM DONTHUOC WHERE MADT = @MADT
IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END


------------------------------------------------------------------

--Taọ proc để lấy toàn bộ thông tin hóa đơn
CREATE PROC SelectAllHoaDon
	@TUKHOA NVARCHAR(50) --tìm kiếm hóa đơn dựa vào từ khóa
	--1. tìm theo mã HÓA ĐƠN
	--2. tìm theo mã BỆNH NHÂN
	--3. tìm theo mã ĐƠN THUỐC
	--4. tìm theo NGÀY LẬP
	--5. tìm theo TỔNG TIỀN
	--6. TÌM THEO TÊN BỆNH NHÂN
	-- loại tìm kiếm tương đối
AS
	SELECT 
		HD.MAHD, BN.TENBN, DT.MADT, CONVERT (VARCHAR (10), HD.NGAYLAP, 103) AS NGAYLAP, --định dạng ngày lập theo dd/mm/yyyy,
		HD.TONGTIEN
	FROM HOADON HD
	JOIN BENHNHAN BN ON HD.MABN = BN.MABN
	JOIN DONTHUOC DT ON HD.MADT = DT.MADT
	WHERE
		CAST(DT.MADT AS VARCHAR(10)) LIKE '%' + LOWER(TRIM(@TUKHOA)) + '%'
		OR LOWER(HD.MAHD) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(BN.MABN) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(BN.TENBN) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(DT.MADT) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(HD.NGAYLAP) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(HD.TONGTIEN) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
	ORDER BY HD.MAHD
GO



--Tạo proc để thêm mới HÓA ĐƠN vào bảng HÓA ĐƠN
CREATE PROC ThemMoiHoaDon
	@mahd VARCHAR(10),
	@mabn VARCHAR(10),
	@madt VARCHAR(10),
	@ngaylap DATE,
	@tongtien FLOAT
AS
BEGIN 
	--THÊM DỮ LIỆU MỚI
	INSERT INTO HOADON
	(
		MAHD,
		MABN,
		MADT,
		NGAYLAP,
	    TONGTIEN
	)
	VALUES
	(
		@mahd,
		@mabn,
		@madt,
		@ngaylap,
		@tongtien
	);
	--KIỂM TRA XEM ĐÃ INSERT THÀNH CÔNG HAY CHƯA
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END





-- TẠO PROCEDURE UPDATE THÔNG TIN hóa đơn
CREATE PROC UpdateHoaDon
	@MAHD VARCHAR(10),
	@MABN VARCHAR(10),
	@MADT VARCHAR(10),
	@NGAYLAP DATE,
	@TONGTIEN FLOAT
AS 
BEGIN
	UPDATE HOADON
	SET
		MAHD=@MAHD,
		MABN=@MABN,
		MADT=@MADT,
		NGAYLAP=@NGAYLAP,
		TONGTIEN=@TONGTIEN
	WHERE MAHD = @MAHD;
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END



--TẠO PROC SELECT THÔNG TIN HÓA ĐƠN
CREATE PROC selectHoaDon
	@MAHD VARCHAR(10)
AS
BEGIN
	SELECT
		MAHD,
		MABN,
		MADT,
		NGAYLAP,
		TONGTIEN
	FROM HOADON
WHERE MAHD=@MAHD;
END



--TẠO PROC ĐỂ XÓA THÔNG TIN HÓA ĐƠN
CREATE PROC DeleteHoaDon
	@MAHD VARCHAR(10)
AS
BEGIN
	DELETE FROM HOADON_DV WHERE MAHD = @MAHD --xóa các chi tiết HÓA ĐƠN-DV LIÊN QUAN TỚI HÓA ĐƠN
	DELETE FROM HOADON WHERE MAHD = @MAHD
IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END





-------------------------------------------------------
--TẠO PROC DANH SACH HÓA ĐƠN ĐÃ LẬP CỦA MỘT BỆNH NHÂN
CREATE PROC HoaDonDaLap
	@TUKHOA NVARCHAR(50) 
AS
BEGIN
	SELECT
		HD.MAHD,BN.TENBN, DV.TENDV, HDDV.SOLUONG AS SOLUONGDV, DT.MADT,BS.TENBS, HD.NGAYLAP, HD.TONGTIEN 
	FROM HOADON HD
	LEFT JOIN HOADON_DV HDDV ON HDDV.MAHD=HD.MAHD
	LEFT JOIN DVKHAM DV ON HDDV.MADV=DV.MADV
	LEFT JOIN BENHNHAN BN ON BN.MABN=HD.MABN
	LEFT JOIN DONTHUOC DT ON HD.MADT=DT.MADT
	LEFT JOIN BACSI BS ON BS.MABS=DT.MABS
	WHERE
		CAST(BN.MABN AS VARCHAR(10)) LIKE '%' + LOWER(TRIM(@TUKHOA)) + '%'
		OR CAST(HD.MAHD AS VARCHAR(10)) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(BN.TENBN) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(DV.TENDV) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(HDDV.SOLUONG) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR CAST(DT.MADT AS VARCHAR(10)) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(BS.TENBS) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(HD.NGAYLAP) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(HD.TONGTIEN) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
	ORDER BY HD.MAHD
END

--TẠO PROC ĐỂ LẬP HÓA ĐƠN MỚI CHO BỆNH NHÂN
--dữ liệu sẽ được lưu ở bảng HOADON_DV
--xác định tham số đầu vào gồm có: mã hóa đơn, mã dịch vụ
CREATE PROC ThemMoiCT_HoaDon
	@mahd VARCHAR(10),
	@madv VARCHAR(10),
	@soluong INT
AS
BEGIN
--THÊM DỮ LIỆU MỚI
	INSERT INTO HOADON_DV
	(
		MAHD,
		MADV,
		SOLUONG
	)
	VALUES
	(
		@mahd,
		@madv,
		@soluong
	);
	--KIỂM TRA XEM ĐÃ INSERT THÀNH CÔNG HAY CHƯA
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END

-- TẠO PROCEDURE UPDATE THÔNG TIN hóa đơn
CREATE PROC UpdateCT_HoaDon
	@MAHD VARCHAR(10),
	@MADV VARCHAR(10),
	@SOLUONG INT
AS 
BEGIN
	UPDATE HOADON_DV
	SET
		MAHD=@MAHD,
		MADV=@MADV,
		SOLUONG=@SOLUONG
	WHERE MAHD = @MAHD;
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END
--TẠO PROC SELECT THÔNG TIN ĐƠN THUỐC
CREATE PROC selectCT_HoaDon
	@MAHD VARCHAR(10)
AS
BEGIN
	SELECT
		MAHD,
		MADV,
		SOLUONG
	FROM HOADON_DV
WHERE MAHD=@MAHD;
END
--tạo proc những bệnh nhân chưa có hóa đơn
CREATE PROC BNChuaCoHoaDon
AS
BEGIN
	SELECT
		BN.MABN, BN.TENBN, BN.TINHTRANGSUCKHOE
	FROM BENHNHAN BN
	LEFT JOIN HOADON HD ON BN.MABN=HD.MABN
	WHERE HD.MABN IS NULL
END
--TẠO PROC ĐỂ XÓA THÔNG TIN HÓA ĐƠN_DỊCH VỤ
CREATE PROC DeleteCT_HoaDon
	@MAHD VARCHAR(10)
AS
BEGIN
	DELETE FROM HOADON WHERE MAHD = @MAHD --xóa các hóa đơn liên quan đến chi tiết HÓA ĐƠN-DV 
	DELETE FROM HOADON_DV WHERE MAHD = @MAHD
IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END







--------------------------------------------------------------------------------------------------------------
--TẠO PROC DANH SACH ĐƠN THUỐC ĐÃ LẬP CỦA MỘT BỆNH NHÂN
CREATE PROC DonThuocDaLap
	@TUKHOA NVARCHAR(50) 
AS
BEGIN
	SELECT
		 DT.MADT, BN.TENBN, BS.TENBS, T.TENTHUOC, CTDT.SOLUONG, T.GIATHUOC
	FROM DONTHUOC DT
	LEFT JOIN CT_DONTHUOC CTDT ON CTDT.MADT=DT.MADT
	LEFT JOIN THUOC T ON CTDT.MATHUOC=T.MATHUOC
	LEFT JOIN BENHNHAN BN ON BN.MABN=DT.MABN
	LEFT JOIN BACSI BS ON BS.MABS=DT.MABS
	WHERE
		CAST(BN.MABN AS VARCHAR(10)) LIKE '%' + LOWER(TRIM(@TUKHOA)) + '%'
		OR CAST(DT.MADT AS VARCHAR(10)) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(BN.TENBN) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(BS.TENBS) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(T.TENTHUOC) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(CTDT.SOLUONG) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
		OR LOWER(T.GIATHUOC) LIKE '%'+LOWER(LTRIM(@TUKHOA)) + '%'
	ORDER BY DT.MADT
END


--TẠO PROC ĐỂ LẬP Đơn thuốc MỚI CHO BỆNH NHÂN

--dữ liệu sẽ được lưu ở bảng CT_DONTHUOC
--xác định tham số đầu vào gồm có: mã đơn thuốc, mã thuốc
CREATE PROC ThemMoiCT_DonThuoc
	@madt VARCHAR(10),
	@mathuoc VARCHAR(10),
	@soluong INT
AS
BEGIN
--THÊM DỮ LIỆU MỚI
	INSERT INTO CT_DONTHUOC
	(
		MADT,
		MATHUOC,
		SOLUONG
	)
	VALUES
	(
		@madt,
		@mathuoc,
		@soluong
	);
	--KIỂM TRA XEM ĐÃ INSERT THÀNH CÔNG HAY CHƯA
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END

-- TẠO PROCEDURE UPDATE THÔNG TIN đơn thuốc
CREATE PROC UpdateCT_DonThuoc
	@MADT VARCHAR(10),
	@MATHUOC VARCHAR(10),
	@SOLUONG INT
AS 
BEGIN
	UPDATE CT_DONTHUOC
	SET
		MADT=@MADT,
		MATHUOC=@MATHUOC,
		SOLUONG=@SOLUONG
	WHERE MADT = @MADT;
	IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END
--TẠO PROC SELECT THÔNG TIN ĐƠN THUỐC
CREATE PROC selectCT_DonThuoc
	@MADT VARCHAR(10)
AS
BEGIN
	SELECT
		MADT,
		MATHUOC,
		SOLUONG
	FROM CT_DONTHUOC
WHERE MADT=@MADT;
END
--tạo proc những bệnh nhân chưa được kê đơn thuốc
CREATE PROC BNChuaCoDonThuoc
AS
BEGIN
	SELECT
		BN.MABN, BN.TENBN, BN.TINHTRANGSUCKHOE
	FROM BENHNHAN BN
	LEFT JOIN DONTHUOC DT ON BN.MABN=DT.MABN
	WHERE DT.MABN IS NULL
END
--TẠO PROC ĐỂ XÓA THÔNG TIN chi tiết đơn thuốc
CREATE PROC DeleteCT_DonThuoc
	@MADT VARCHAR(10)
AS
BEGIN
	DELETE FROM DONTHUOC WHERE MADT = @MADT --xóa các đơn thuốc LIÊN QUAN TỚI CT_đơn thuốc
	DELETE FROM CT_DONTHUOC WHERE MADT = @MADT
IF @@ROWCOUNT >0 BEGIN RETURN 1 END --NẾU INSERT THÀNH CÔNG TRẢ VỀ 1
	ELSE BEGIN RETURN 0 END; -- NGƯỢC LẠI RETURN 0
END

